/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AokiGame: typeof import('./src/components/AokiGame.vue')['default']
    AokiPage: typeof import('./src/components/aoki/AokiPage.vue')['default']
    AokiPage1: typeof import('./src/components/aoki/AokiPage1.vue')['default']
    AokiPage2: typeof import('./src/components/aoki/AokiPage2.vue')['default']
    Count: typeof import('./src/components/Count.vue')['default']
    Enemy: typeof import('./src/components/enemy.vue')['default']
    Game: typeof import('./src/components/game.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Janken: typeof import('./src/components/Sendenemy.vue')['default']
    JunkenGame: typeof import('./src/components/junkenGame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screen: typeof import('./src/components/Screen.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    Sendenemy: typeof import('./src/components/Sendenemy.vue')['default']
    SendEnemy: typeof import('./src/components/Send-enemy.vue')['default']
    Start: typeof import('./src/components/Start.vue')['default']
    System: typeof import('./src/components/system.vue')['default']
    Wim: typeof import('./src/components/wim.vue')['default']
    Win: typeof import('./src/components/win.vue')['default']
  }
}
